// <auto-generated />
using System;
using Lyubishchev_Time_Management.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lyubishchev_Time_Management.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Lyubishchev_Time_Management.Models.Entities.Category", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Lyubishchev_Time_Management.Models.Entities.RunningTimer", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("RunningTimers", (string)null);
                });

            modelBuilder.Entity("Lyubishchev_Time_Management.Models.Entities.Tag", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Lyubishchev_Time_Management.Models.Entities.TimeEntry", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("CategoryId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "StartTimeUtc");

                    b.HasIndex("UserId", "CategoryId", "StartTimeUtc");

                    b.ToTable("TimeEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_TimeEntries_EndTimeUtc_After_StartTimeUtc", "`EndTimeUtc` > `StartTimeUtc`");
                        });
                });

            modelBuilder.Entity("Lyubishchev_Time_Management.Models.Entities.TimeEntryTag", b =>
                {
                    b.Property<ulong>("TimeEntryId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("TagId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("TimeEntryId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TimeEntryTags", (string)null);
                });

            modelBuilder.Entity("Lyubishchev_Time_Management.Models.Entities.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Lyubishchev_Time_Management.Models.Entities.Category", b =>
                {
                    b.HasOne("Lyubishchev_Time_Management.Models.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lyubishchev_Time_Management.Models.Entities.RunningTimer", b =>
                {
                    b.HasOne("Lyubishchev_Time_Management.Models.Entities.User", "User")
                        .WithOne("RunningTimer")
                        .HasForeignKey("Lyubishchev_Time_Management.Models.Entities.RunningTimer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lyubishchev_Time_Management.Models.Entities.Tag", b =>
                {
                    b.HasOne("Lyubishchev_Time_Management.Models.Entities.User", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lyubishchev_Time_Management.Models.Entities.TimeEntry", b =>
                {
                    b.HasOne("Lyubishchev_Time_Management.Models.Entities.Category", "Category")
                        .WithMany("TimeEntries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lyubishchev_Time_Management.Models.Entities.User", "User")
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lyubishchev_Time_Management.Models.Entities.TimeEntryTag", b =>
                {
                    b.HasOne("Lyubishchev_Time_Management.Models.Entities.Tag", "Tag")
                        .WithMany("TimeEntryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyubishchev_Time_Management.Models.Entities.TimeEntry", "TimeEntry")
                        .WithMany("TimeEntryTags")
                        .HasForeignKey("TimeEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("TimeEntry");
                });

            modelBuilder.Entity("Lyubishchev_Time_Management.Models.Entities.Category", b =>
                {
                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("Lyubishchev_Time_Management.Models.Entities.Tag", b =>
                {
                    b.Navigation("TimeEntryTags");
                });

            modelBuilder.Entity("Lyubishchev_Time_Management.Models.Entities.TimeEntry", b =>
                {
                    b.Navigation("TimeEntryTags");
                });

            modelBuilder.Entity("Lyubishchev_Time_Management.Models.Entities.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("RunningTimer");

                    b.Navigation("Tags");

                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
